color0 #45474b
color1 #ffb4ab
color2 #c2c7cf
color3 #c6c6ca
color4 #d0c3cd
color5 #c2c7cf
color6 #c6c6ca
color7 #e5e2e2
color8 #8f9195
color9 #ffb4ab
color10 #c2c7cf
color11 #c6c6ca
color12 #d0c3cd
color13 #c2c7cf
color14 #c6c6ca
color15 #e5e2e2

cursor                #e5e2e2
cursor_text_color     #131314
background            #131314
foreground            #e5e2e2
selection_foreground  #c5c6cb
selection_background  #45474b
active_border_color   #c2c7cf
inactive_border_color #45474b
url_color             #c2c7cf

active_tab_foreground   #2c3138
active_tab_background   #c2c7cf
inactive_tab_foreground #c5c6cb
inactive_tab_background #45474b
cursor_trail_color      #c5c6cb
